[project]
name = "schuiver"
version = "0.1.0"
description = "Een eenvoudig schuiverprogramma"
readme = "README.md"
requires-python = "==3.14.2"
dependencies = [
    "pygame-ce==2.5.6",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
